name: iOS-simulator-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸ§ª iOS Simulator Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS for simulator
        run: flutter build ios --simulator --release

      - name: Prepare IPA structure
        run: |
          mkdir Payload
          mv Runner.app Payload/
        working-directory: build/ios/iphonesimulator

      - name: Create simulator IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphonesimulator

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphonesimulator/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Simulator build IPA (for experimental sideloading use only)"
