name: iOS-ipa-build-simulator

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸ§© iOS Simulator Build (Unsigned IPA)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get dependencies
        run: flutter pub get

      - name: Build for Simulator (Debug mode)
        run: flutter build ios --simulator --debug

      - name: Prepare Payload folder
        run: |
          mkdir -p build/ios/iphonesimulator/Payload
          cp -R build/ios/iphonesimulator/Runner.app build/ios/iphonesimulator/Payload/

      - name: Create IPA from Payload
        run: |
          cd build/ios/iphonesimulator
          zip -r -9 FlutterIpaExport.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlutterIpaExport
          path: build/ios/iphonesimulator/FlutterIpaExport.ipa
